spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

openrouter.api.key=your-api
openrouter.url=your-url

qdrant.url=your-url
qdrant.api.key=your-api

jina.api.key=your-api
jina.embedding.url=your-api

spring.security.oauth2.client.registration.google.client-id=your-id
spring.security.oauth2.client.registration.google.client-secret=your-secret
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=your-url
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
server.port=your-port
# Frontend URL for OAuth redirect
app.frontend-url=your-url